version: '3.4'

services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: euvsvirus
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  db_data:
    external: true