version: '3.4'

services:
  db-mysql:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: euvsvirus
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  proxy_osint_api:
    restart: always
    image: proxy_covid_blacklist:${project.version}
    ports:
      - 9080:9080
  main_api:
    restart: always
    image: fnh_api:${project.version}
    ports:
      - 7080:7080
  hammer-service:
    restart: always
    image: hammer-service:${project.version}
    ports:
      - 8080:8080 # web-server port
      - 8888:8888 # DEBUG port, e.g. IntelliJ remote debug
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
      JAVA_OPTS: "
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888
                 "
    #        -Ddatasource.url=jdbc:mysql://db-mysql:3306/euvsvirus
    #        -Ddatasource.username=user
    #        -Ddatasource.password=password
    #        -Ddatasource.driver-class-name=com.mysql.cj.jdbc.Driver
    #        -Djpa.generate-ddl=true
    #        -Djpa.hibernate.ddl-auto=update
    #        -Djpa.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
    #                 "
    depends_on:
      - db-mysql
    links:
      - db-mysql
  ui-service:
    restart: always
    image: ${docker.registry.prefix}ui-service:${project.version}
  ingress-docker:
    restart: always
    image: ${docker.registry.prefix}ingress-docker:${project.version}
    ports:
      - 80:80
    depends_on:
      - db-mysql
      - ui-service
      - hammer-service
    links:
      - db-mysql
      - ui-service
      - hammer-service
volumes:
  db_data:
    external: true
