version: '3.4'

services:
  db-mysql:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: euvsvirus
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  proxy_osint_api:
    restart: always
    image: proxy_covid_blacklist:${project.version}
    build:
      dockerfile: ./Dockerfile
      context: ../../../../proxy_osint_api
  main_api:
    restart: always
    image: fnh_api:${project.version}
    build:
      dockerfile: ./Dockerfile
      context: ../../../../main_api
  hammer-service:
    restart: always
    image: hammer-service:${project.version}
    build:
      dockerfile: ./Dockerfile
      context: ../../../../hammer-service
    depends_on:
      - db-mysql
    links:
      - db-mysql
  ui-service:
    restart: always
    image: ${docker.registry.prefix}ui-service:${project.version}
    build:
      dockerfile: ./Dockerfile
      context: ../../../../ui-service
  ingress-docker:
    restart: always
    image: ${docker.registry.prefix}ingress-docker:${project.version}
    build:
      dockerfile: ./Dockerfile
      context: ../../../../ingress-docker/target
    ports:
      - 80:80
    depends_on:
      - db-mysql
      - ui-service
      - hammer-service
    links:
      - db-mysql
      - ui-service
      - hammer-service
volumes:
  db_data:
    external: true
