# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class DashboardStatistics(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, time: datetime=None, social_media_links: int=None, social_media_links_diff: int=None, article_links: int=None, article_links_diff: int=None, content_rewiew_tasks: int=None, content_rewiew_tasks_diff: int=None, potential_fake_news_sites: int=None, potential_fake_news_sites_diff: int=None, indexed_sites: int=None, indexed_sites_diff: int=None, indexed_articles_month: int=None, indexed_articles_month_diff: int=None):  # noqa: E501
        """DashboardStatistics - a model defined in Swagger

        :param time: The time of this DashboardStatistics.  # noqa: E501
        :type time: datetime
        :param social_media_links: The social_media_links of this DashboardStatistics.  # noqa: E501
        :type social_media_links: int
        :param social_media_links_diff: The social_media_links_diff of this DashboardStatistics.  # noqa: E501
        :type social_media_links_diff: int
        :param article_links: The article_links of this DashboardStatistics.  # noqa: E501
        :type article_links: int
        :param article_links_diff: The article_links_diff of this DashboardStatistics.  # noqa: E501
        :type article_links_diff: int
        :param content_rewiew_tasks: The content_rewiew_tasks of this DashboardStatistics.  # noqa: E501
        :type content_rewiew_tasks: int
        :param content_rewiew_tasks_diff: The content_rewiew_tasks_diff of this DashboardStatistics.  # noqa: E501
        :type content_rewiew_tasks_diff: int
        :param potential_fake_news_sites: The potential_fake_news_sites of this DashboardStatistics.  # noqa: E501
        :type potential_fake_news_sites: int
        :param potential_fake_news_sites_diff: The potential_fake_news_sites_diff of this DashboardStatistics.  # noqa: E501
        :type potential_fake_news_sites_diff: int
        :param indexed_sites: The indexed_sites of this DashboardStatistics.  # noqa: E501
        :type indexed_sites: int
        :param indexed_sites_diff: The indexed_sites_diff of this DashboardStatistics.  # noqa: E501
        :type indexed_sites_diff: int
        :param indexed_articles_month: The indexed_articles_month of this DashboardStatistics.  # noqa: E501
        :type indexed_articles_month: int
        :param indexed_articles_month_diff: The indexed_articles_month_diff of this DashboardStatistics.  # noqa: E501
        :type indexed_articles_month_diff: int
        """
        self.swagger_types = {
            'time': datetime,
            'social_media_links': int,
            'social_media_links_diff': int,
            'article_links': int,
            'article_links_diff': int,
            'content_rewiew_tasks': int,
            'content_rewiew_tasks_diff': int,
            'potential_fake_news_sites': int,
            'potential_fake_news_sites_diff': int,
            'indexed_sites': int,
            'indexed_sites_diff': int,
            'indexed_articles_month': int,
            'indexed_articles_month_diff': int
        }

        self.attribute_map = {
            'time': 'time',
            'social_media_links': 'social-media-links',
            'social_media_links_diff': 'social-media-links-diff',
            'article_links': 'article-links',
            'article_links_diff': 'article-links-diff',
            'content_rewiew_tasks': 'content-rewiew-tasks',
            'content_rewiew_tasks_diff': 'content-rewiew-tasks-diff',
            'potential_fake_news_sites': 'potential-fake-news-sites',
            'potential_fake_news_sites_diff': 'potential-fake-news-sites-diff',
            'indexed_sites': 'indexed-sites',
            'indexed_sites_diff': 'indexed-sites-diff',
            'indexed_articles_month': 'indexed-articles-month',
            'indexed_articles_month_diff': 'indexed-articles-month-diff'
        }

        self._time = time
        self._social_media_links = social_media_links
        self._social_media_links_diff = social_media_links_diff
        self._article_links = article_links
        self._article_links_diff = article_links_diff
        self._content_rewiew_tasks = content_rewiew_tasks
        self._content_rewiew_tasks_diff = content_rewiew_tasks_diff
        self._potential_fake_news_sites = potential_fake_news_sites
        self._potential_fake_news_sites_diff = potential_fake_news_sites_diff
        self._indexed_sites = indexed_sites
        self._indexed_sites_diff = indexed_sites_diff
        self._indexed_articles_month = indexed_articles_month
        self._indexed_articles_month_diff = indexed_articles_month_diff

    @classmethod
    def from_dict(cls, dikt) -> 'DashboardStatistics':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Dashboard-Statistics of this DashboardStatistics.  # noqa: E501
        :rtype: DashboardStatistics
        """
        return util.deserialize_model(dikt, cls)

    @property
    def time(self) -> datetime:
        """Gets the time of this DashboardStatistics.


        :return: The time of this DashboardStatistics.
        :rtype: datetime
        """
        return self._time

    @time.setter
    def time(self, time: datetime):
        """Sets the time of this DashboardStatistics.


        :param time: The time of this DashboardStatistics.
        :type time: datetime
        """

        self._time = time

    @property
    def social_media_links(self) -> int:
        """Gets the social_media_links of this DashboardStatistics.


        :return: The social_media_links of this DashboardStatistics.
        :rtype: int
        """
        return self._social_media_links

    @social_media_links.setter
    def social_media_links(self, social_media_links: int):
        """Sets the social_media_links of this DashboardStatistics.


        :param social_media_links: The social_media_links of this DashboardStatistics.
        :type social_media_links: int
        """

        self._social_media_links = social_media_links

    @property
    def social_media_links_diff(self) -> int:
        """Gets the social_media_links_diff of this DashboardStatistics.


        :return: The social_media_links_diff of this DashboardStatistics.
        :rtype: int
        """
        return self._social_media_links_diff

    @social_media_links_diff.setter
    def social_media_links_diff(self, social_media_links_diff: int):
        """Sets the social_media_links_diff of this DashboardStatistics.


        :param social_media_links_diff: The social_media_links_diff of this DashboardStatistics.
        :type social_media_links_diff: int
        """

        self._social_media_links_diff = social_media_links_diff

    @property
    def article_links(self) -> int:
        """Gets the article_links of this DashboardStatistics.


        :return: The article_links of this DashboardStatistics.
        :rtype: int
        """
        return self._article_links

    @article_links.setter
    def article_links(self, article_links: int):
        """Sets the article_links of this DashboardStatistics.


        :param article_links: The article_links of this DashboardStatistics.
        :type article_links: int
        """

        self._article_links = article_links

    @property
    def article_links_diff(self) -> int:
        """Gets the article_links_diff of this DashboardStatistics.


        :return: The article_links_diff of this DashboardStatistics.
        :rtype: int
        """
        return self._article_links_diff

    @article_links_diff.setter
    def article_links_diff(self, article_links_diff: int):
        """Sets the article_links_diff of this DashboardStatistics.


        :param article_links_diff: The article_links_diff of this DashboardStatistics.
        :type article_links_diff: int
        """

        self._article_links_diff = article_links_diff

    @property
    def content_rewiew_tasks(self) -> int:
        """Gets the content_rewiew_tasks of this DashboardStatistics.


        :return: The content_rewiew_tasks of this DashboardStatistics.
        :rtype: int
        """
        return self._content_rewiew_tasks

    @content_rewiew_tasks.setter
    def content_rewiew_tasks(self, content_rewiew_tasks: int):
        """Sets the content_rewiew_tasks of this DashboardStatistics.


        :param content_rewiew_tasks: The content_rewiew_tasks of this DashboardStatistics.
        :type content_rewiew_tasks: int
        """

        self._content_rewiew_tasks = content_rewiew_tasks

    @property
    def content_rewiew_tasks_diff(self) -> int:
        """Gets the content_rewiew_tasks_diff of this DashboardStatistics.


        :return: The content_rewiew_tasks_diff of this DashboardStatistics.
        :rtype: int
        """
        return self._content_rewiew_tasks_diff

    @content_rewiew_tasks_diff.setter
    def content_rewiew_tasks_diff(self, content_rewiew_tasks_diff: int):
        """Sets the content_rewiew_tasks_diff of this DashboardStatistics.


        :param content_rewiew_tasks_diff: The content_rewiew_tasks_diff of this DashboardStatistics.
        :type content_rewiew_tasks_diff: int
        """

        self._content_rewiew_tasks_diff = content_rewiew_tasks_diff

    @property
    def potential_fake_news_sites(self) -> int:
        """Gets the potential_fake_news_sites of this DashboardStatistics.


        :return: The potential_fake_news_sites of this DashboardStatistics.
        :rtype: int
        """
        return self._potential_fake_news_sites

    @potential_fake_news_sites.setter
    def potential_fake_news_sites(self, potential_fake_news_sites: int):
        """Sets the potential_fake_news_sites of this DashboardStatistics.


        :param potential_fake_news_sites: The potential_fake_news_sites of this DashboardStatistics.
        :type potential_fake_news_sites: int
        """

        self._potential_fake_news_sites = potential_fake_news_sites

    @property
    def potential_fake_news_sites_diff(self) -> int:
        """Gets the potential_fake_news_sites_diff of this DashboardStatistics.


        :return: The potential_fake_news_sites_diff of this DashboardStatistics.
        :rtype: int
        """
        return self._potential_fake_news_sites_diff

    @potential_fake_news_sites_diff.setter
    def potential_fake_news_sites_diff(self, potential_fake_news_sites_diff: int):
        """Sets the potential_fake_news_sites_diff of this DashboardStatistics.


        :param potential_fake_news_sites_diff: The potential_fake_news_sites_diff of this DashboardStatistics.
        :type potential_fake_news_sites_diff: int
        """

        self._potential_fake_news_sites_diff = potential_fake_news_sites_diff

    @property
    def indexed_sites(self) -> int:
        """Gets the indexed_sites of this DashboardStatistics.


        :return: The indexed_sites of this DashboardStatistics.
        :rtype: int
        """
        return self._indexed_sites

    @indexed_sites.setter
    def indexed_sites(self, indexed_sites: int):
        """Sets the indexed_sites of this DashboardStatistics.


        :param indexed_sites: The indexed_sites of this DashboardStatistics.
        :type indexed_sites: int
        """

        self._indexed_sites = indexed_sites

    @property
    def indexed_sites_diff(self) -> int:
        """Gets the indexed_sites_diff of this DashboardStatistics.


        :return: The indexed_sites_diff of this DashboardStatistics.
        :rtype: int
        """
        return self._indexed_sites_diff

    @indexed_sites_diff.setter
    def indexed_sites_diff(self, indexed_sites_diff: int):
        """Sets the indexed_sites_diff of this DashboardStatistics.


        :param indexed_sites_diff: The indexed_sites_diff of this DashboardStatistics.
        :type indexed_sites_diff: int
        """

        self._indexed_sites_diff = indexed_sites_diff

    @property
    def indexed_articles_month(self) -> int:
        """Gets the indexed_articles_month of this DashboardStatistics.


        :return: The indexed_articles_month of this DashboardStatistics.
        :rtype: int
        """
        return self._indexed_articles_month

    @indexed_articles_month.setter
    def indexed_articles_month(self, indexed_articles_month: int):
        """Sets the indexed_articles_month of this DashboardStatistics.


        :param indexed_articles_month: The indexed_articles_month of this DashboardStatistics.
        :type indexed_articles_month: int
        """

        self._indexed_articles_month = indexed_articles_month

    @property
    def indexed_articles_month_diff(self) -> int:
        """Gets the indexed_articles_month_diff of this DashboardStatistics.


        :return: The indexed_articles_month_diff of this DashboardStatistics.
        :rtype: int
        """
        return self._indexed_articles_month_diff

    @indexed_articles_month_diff.setter
    def indexed_articles_month_diff(self, indexed_articles_month_diff: int):
        """Sets the indexed_articles_month_diff of this DashboardStatistics.


        :param indexed_articles_month_diff: The indexed_articles_month_diff of this DashboardStatistics.
        :type indexed_articles_month_diff: int
        """

        self._indexed_articles_month_diff = indexed_articles_month_diff
