# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .evaluation import Evaluation

from swagger_server.models.base_model_ import Model
from swagger_server import util


class QueryResponse(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, time: datetime=None, source_api: str=None, evaluations: List[Evaluation]=None):  # noqa: E501
        """QueryResponse - a model defined in Swagger

        :param time: The time of this QueryResponse.  # noqa: E501
        :type time: datetime
        :param source_api: The source_api of this QueryResponse.  # noqa: E501
        :type source_api: str
        :param evaluations: The evaluations of this QueryResponse.  # noqa: E501
        :type evaluations: List[Evaluation]
        """
        self.swagger_types = {
            'time': datetime,
            'source_api': str,
            'evaluations': List[Evaluation]
        }

        self.attribute_map = {
            'time': 'time',
            'source_api': 'source-api',
            'evaluations': 'evaluations'
        }

        self._time = time
        self._source_api = source_api
        self._evaluations = evaluations

    @classmethod
    def from_dict(cls, dikt) -> 'QueryResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The QueryResponse of this QueryResponse.  # noqa: E501
        :rtype: QueryResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def time(self) -> datetime:
        """Gets the time of this QueryResponse.


        :return: The time of this QueryResponse.
        :rtype: datetime
        """
        return self._time

    @time.setter
    def time(self, time: datetime):
        """Sets the time of this QueryResponse.


        :param time: The time of this QueryResponse.
        :type time: datetime
        """

        self._time = time

    @property
    def source_api(self) -> str:
        """Gets the source_api of this QueryResponse.


        :return: The source_api of this QueryResponse.
        :rtype: str
        """
        return self._source_api

    @source_api.setter
    def source_api(self, source_api: str):
        """Sets the source_api of this QueryResponse.


        :param source_api: The source_api of this QueryResponse.
        :type source_api: str
        """

        self._source_api = source_api

    @property
    def evaluations(self) -> List[Evaluation]:
        """Gets the evaluations of this QueryResponse.


        :return: The evaluations of this QueryResponse.
        :rtype: List[Evaluation]
        """
        return self._evaluations

    @evaluations.setter
    def evaluations(self, evaluations: List[Evaluation]):
        """Sets the evaluations of this QueryResponse.


        :param evaluations: The evaluations of this QueryResponse.
        :type evaluations: List[Evaluation]
        """

        self._evaluations = evaluations
